collections:
  - name: community.general
    version: 8.6.0
  - name: scale_computing.hypercore
    version: 1.5.0
  - name: kubernetes.core
    version: 3.0.1
roles:
  - name: geerlingguy.nfs
    version: 2.0.0
