collections:
  - name: community.general
    version: 8.6.0
  - name: scale_computing.hypercore
    version: 1.4.0 # 1.5.0 - url2template role is needed
roles:
  - name: geerlingguy.nfs
    version: 2.0.0
