---
# Prevents "undefined hostvars" error
- name: Dummy play
  hosts: k3s_cluster
  gather_facts: false
  tasks: []

- name: Install MetalLB
  hosts: "{{ hostvars[groups['server'][0]]['inventory_hostname'] }}"
  gather_facts: false
  tasks:

    - name: Add MetalLB chart repo
      kubernetes.core.helm_repository:
        name: metallb
        repo_url: https://metallb.github.io/metallb/

    - name: Install MetalLB
      kubernetes.core.helm:
        name: metallb
        chart_ref: metallb/metallb
        chart_version: 0.14.5
        release_namespace: metallb-system
        create_namespace: true

    - name: Wait for MetalLB to be up before adding pool
      ansible.builtin.pause:
        seconds: 10

    - name: Configure MetalLB IP pool
      kubernetes.core.k8s:
        template: metallb-pool.yml.j2
        state: present
      # register: metallb_pool_result
      # until: metallb_pool_result is succeeded
      delay: 10
      retries: 10
