---
# Prevents "undefined hostvars" error
- name: Dummy play
  hosts: k3s_cluster
  gather_facts: false
  tasks: []

- name: Install external DNS service
  hosts: "{{ hostvars[groups['server'][0]]['inventory_hostname'] }}"
  gather_facts: false
  tasks:
    - name: Add k8s_gateway chart repo
      kubernetes.core.helm_repository:
        name: k8s_gateway
        repo_url: https://ori-edge.github.io/k8s_gateway/

    - name: Install k8s_gateway for DNS domain xyz.si
      kubernetes.core.helm:
        name: exdns
        chart_ref: k8s_gateway/k8s-gateway
        chart_version: 2.4.0
        release_namespace: kube-system
        set_values:
          - value: domain=xyz.si
            value_type: string
