---
- name: Install NFS utils
  hosts: k3s_cluster
  gather_facts: false
  tasks:
    - name: Add NFS client utils - mount.nfs
      ansible.builtin.package:
        name: nfs-common
        state: present
