---
- name: Create K3s NFS server VMs
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create K3s NFS server
      ansible.builtin.include_role:
        name: scale_computing.hypercore.template2vm
      vars:
        template2vm_source_vm_name: "{{ source_vm_name }}"
        template2vm_vm_name: "{{ vm_group }}-nfs-server"
        template2vm_description: NFS server, created from {{ source_vm_name }}
        template2vm_vm_tags:
          - "{{ vm_group }}"
          - ansible_group__{{ vm_group }}
          - ansible_group__{{ vm_group }}_nfs_servers
          - ansible_host__{{ nfs_ip_address }}
          - ansible_user__ubuntu
          # - SERIAL
        template2vm_vcpu: "{{ vcpu }}"
        template2vm_memory: "{{ memory }}"
        template2vm_disk_size: "{{ disk_size }}"
        template2vm_power_state: start
        # cloud-init
        template2vm_user_data: "{{ lookup('template', 'user-data.ubuntu-22.04.yml.j2') }}"
        template2vm_meta_data: "{{ lookup('template', 'meta-data.ubuntu-22.04.yml.j2') }}"
        vm_name: "{{ template2vm_vm_name }}"
        vm_network_ip_address: "{{ nfs_ip_address }}"

    - name: Refresh inventory
      ansible.builtin.meta: refresh_inventory

- name: Wait on VM to boot
  hosts: "{{ vm_group }}_nfs_servers"
  gather_facts: false
  tasks:
    - name: Refresh inventory and wait
      ansible.builtin.include_role:
        name: scale_computing.hypercore.template2vm
        tasks_from: wait_vm_boot_tasks.yml
      loop: "{{ range(10) }}"

- name: Setup NFS server
  hosts: "{{ vm_group }}_nfs_servers"
  pre_tasks:
    - name: wait on cloudinit to finish
      ansible.builtin.command: cloud-init status --wait
      async: 600
      poll: 10
      # "journalctl -u cloud-init-local.service" and "cloud-init schema --system"
      # tell us about "'_orig_eni_name' was unexpected" in
      # /var/lib/cloud/instance/network-config.json
      # Ignore this.
      ignore_errors: true
      changed_when: false
  roles:
    - role: geerlingguy.nfs
      become: true
  vars:
    nfs_exports:
      - "{{ nfs_data_dir }}/nfs-client    *(rw,sync,no_root_squash)"
      - "{{ nfs_data_dir }}/nfs-retain    *(rw,sync,no_root_squash)"
